## Pacng.toml

###################
# General Options #
###################
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = "/"
#DBPath      = "/var/lib/pacman/"
#CacheDir    = "/var/cache/pacman/pkg/"
#LogFile     = "/var/log/pacman.log"
#GPGDir      = "/etc/pacman.d/gnupg/"
#HookDir     = "/etc/pacman.d/hooks/"
HoldPkg     = ["pacman", "glibc"]
#CleanMethod = "KeepInstalled"
#UseDelta    = "0.7"
Architecture = "auto"
# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
#IgnorePkg   = []
#IgnoreGroup = []

#NoUpgrade   = []
#NoExtract   = []

# Misc options
Misc = [
  #"UseSyslog",
  "Color",
  #"TotalDownload"
  "CheckSpace"
  #"VerbosePkgLists"
]

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
SigLevel    = ["Required", "DatabaseOptional"]
LocalFileSigLevel = ["Optional"]
#RemoteFileSigLevel = [ "Required "]"

# NOTE: You must run `pacman-key --init` before first using pacng; the local
# keyring can then be populated with the keys of all official Arch Linux
# packagers with `pacman-key --populate archlinux`.

################
# Repositories #
################
#   - can be defined here or included from another file
#   - pacng will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages
#     have identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#   - URLs will have $arch replaced by the name of the architecture
#
# Repository entries are of the format:
#       [repository.RepositoryName]
#       Server = ServerName
#       Include = IncludePath
#
# Or:
#       [[respository]]
#       Name = RepositoryName
#       Server = ServerName
#       Include = IncludePath
#
# The header [repositoryies.repo-name] is crucial - it must be present and
# uncommented to enable the repo.
#

# The testing repositories are disabled by default. To enable, uncomment the
# repo name header and Include lines. You can add preferred servers immediately
# after the header, and they will be used before the default mirrors.

#[repository.testing]
#Include = /etc/pacman.d/mirrorlist

[[repository]]
Name = "core"
Include = "/etc/pacman.d/mirrorlist"

[[repository]]
Name = "extra"
Include = "/etc/pacman.d/mirrorlist"

[[repository]]
Name = "community"
Include = "/etc/pacman.d/mirrorlist"

# [[repository]]
# Name = "community-testing"
# Include = /etc/pacman.d/mirrorlist

# If you want to run 32 bit applications on your x86_64 system,
# enable the multilib repositories as required here.

# [[repository]]
# Name = "multilib-testing"
# Include = /etc/pacman.d/mirrorlist

[[repository]]
Name = "multilib"
Include = "/etc/pacman.d/mirrorlist"

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
# [[repository]]
# Name = "custom"
# SigLevel = ["Optional", "TrustAll"]
# Server = "file:///home/custompkgs"
